In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier

#Evaluating performance
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from IPython.display import display

df = pd.read_csv("data/maps-synthetic-data-v1.1.csv", index_col='X')
pd.options.display.max_columns = None
display(df)

Unnamed: 0       flag comp_bed_9  mat_dep mat_age  weight_16  \
X                                                                     
1               1  synthetic        NaN      3.0      30  59.294132   
2               2  synthetic        NaN      9.0      26        NaN   
3               3  synthetic        NaN      3.0      24        NaN   
4               4  synthetic         No      NaN      22  49.812426   
5               5  synthetic         No      8.0      31  62.270030   
...           ...        ...        ...      ...     ...        ...   
13730       13730  synthetic        NaN     13.0      27        NaN   
13731       13731  synthetic         No      6.0      29        NaN   
13732       13732  synthetic        NaN     21.0      37  58.075832   
13733       13733  synthetic         No     10.0      30        NaN   
13734       13734  synthetic         No      6.0      26  70.732913   

        height_16     iq comp_noint_bed_16 comp_int_bed_16 talk_phon_wend  \
X                                                                           
1      181.602831  107.0               NaN             NaN     Any at all   
2             NaN   85.0               NaN             NaN            NaN   
3             NaN    NaN               NaN             NaN            NaN   
4      160.224186    NaN               NaN             NaN            NaN   
5      191.703227  132.0               Yes             NaN     Not at all   
...           ...    ...               ...             ...            ...   
13730         NaN    NaN               NaN             NaN            NaN   
13731         NaN    NaN               NaN             NaN     Not at all   
13732  169.235565  108.0               NaN             NaN     Any at all   
13733         NaN  103.0               NaN             NaN     Any at all   
13734  176.873882  102.0               NaN             NaN            NaN   

              text_wend     talk_mob_wend         comp_wend   musi_wend  \
X                                                                         
1      Less than 1 hour  Less than 1 hour         1-2 hours  Not at all   
2                   NaN               NaN               NaN         NaN   
3                   NaN               NaN               NaN         NaN   
4                   NaN               NaN               NaN         NaN   
5            Not at all        Not at all  Less than 1 hour  Not at all   
...                 ...               ...               ...         ...   
13730               NaN               NaN               NaN         NaN   
13731  Less than 1 hour  Less than 1 hour         1-2 hours  Any at all   
13732         1-2 hours   1 or more hours         1-2 hours  Not at all   
13733         1-2 hours        Not at all         1-2 hours  Any at all   
13734               NaN               NaN               NaN         NaN   

              read_wend         work_wend        alon_wend         draw_wend  \
X                                                                              
1      Less than 1 hour   3 or more hours        1-2 hours        Not at all   
2                   NaN               NaN              NaN               NaN   
3                   NaN               NaN              NaN               NaN   
4                   NaN               NaN              NaN               NaN   
5       1 or more hours         1-2 hours  3 or more hours        Not at all   
...                 ...               ...              ...               ...   
13730               NaN               NaN              NaN               NaN   
13731  Less than 1 hour         1-2 hours  3 or more hours  Less than 1 hour   
13732        Not at all  Less than 1 hour        1-2 hours  Less than 1 hour   
13733        Not at all         1-2 hours        1-2 hours  Less than 1 hour   
13734               NaN               NaN              NaN               NaN   

               play_wend           tv_wend      out_win_wend  \


In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)
display(dataset)

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
#Divide dataset into features and corresponding labels.
X = dataset.iloc[:, 0:4].values # first 4 cols assigned to X
y = dataset.iloc[:, 4].values # last col assigned to Y

In [4]:
#Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [5]:
#Similar to PCA - perform feature scaling for LDA
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
#Perform LDA using sklearn
lda = LDA(n_components=1) #n_components refers to num of linear discriminants
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [7]:
# Training and making predicitons
classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [8]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy: 1.0


With one linear discriminant algorithm achieved an accuracy of 100% which is greater than 